USE [ReallyBigGameDatabase]
GO

/****** Object:  Table [dbo].[Likes]    Script Date: 2/18/2017 5:25:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Likes](
	[Uname] [char](25) NOT NULL,
	[Game_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Uname] ASC,
	[Game_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Likes]  WITH CHECK ADD  CONSTRAINT [FK_Likes_Games] FOREIGN KEY([Game_id])
REFERENCES [dbo].[Game] ([Game_id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Likes] CHECK CONSTRAINT [FK_Likes_Games]
GO

ALTER TABLE [dbo].[Likes]  WITH CHECK ADD  CONSTRAINT [FK_Likes_Users] FOREIGN KEY([Uname])
REFERENCES [dbo].[Users] ([Uname])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Likes] CHECK CONSTRAINT [FK_Likes_Users]
GO

