USE [ReallyBigGameDatabase]
GO

/****** Object:  Table [dbo].[Mod]    Script Date: 2/18/2017 5:25:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Mod](
	[M_id] [int] IDENTITY(1,1) NOT NULL,
	[MName] [char](50) NOT NULL,
	[Game_id] [int] NULL,
 CONSTRAINT [PK_Mod] PRIMARY KEY CLUSTERED 
(
	[M_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Mod]  WITH CHECK ADD  CONSTRAINT [FK_Mod_Game] FOREIGN KEY([Game_id])
REFERENCES [dbo].[Game] ([Game_id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Mod] CHECK CONSTRAINT [FK_Mod_Game]
GO

