USE [ReallyBigGameDatabase]
GO

/****** Object:  Table [dbo].[Mod_Is_In]    Script Date: 2/18/2017 5:26:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Mod_Is_In](
	[M_id] [int] NOT NULL,
	[TName] [char](20) NOT NULL,
	[percentage] [float] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Mod_Is_In]  WITH CHECK ADD  CONSTRAINT [FK_Mod_Is_In_Mod] FOREIGN KEY([M_id])
REFERENCES [dbo].[Mod] ([M_id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Mod_Is_In] CHECK CONSTRAINT [FK_Mod_Is_In_Mod]
GO

ALTER TABLE [dbo].[Mod_Is_In]  WITH CHECK ADD  CONSTRAINT [FK_Mod_Is_In_Tag] FOREIGN KEY([TName])
REFERENCES [dbo].[Tag] ([TName])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Mod_Is_In] CHECK CONSTRAINT [FK_Mod_Is_In_Tag]
GO

