USE [ReallyBigGameDatabase]
GO

/****** Object:  Table [dbo].[Categorizes]    Script Date: 2/18/2017 5:24:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Categorizes](
	[R_id] [int] NOT NULL,
	[TName] [char](20) NOT NULL,
 CONSTRAINT [PK_Categorizes] PRIMARY KEY CLUSTERED 
(
	[R_id] ASC,
	[TName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Categorizes]  WITH CHECK ADD  CONSTRAINT [FK_Categorizes_Review] FOREIGN KEY([R_id])
REFERENCES [dbo].[Review] ([R_id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Categorizes] CHECK CONSTRAINT [FK_Categorizes_Review]
GO

ALTER TABLE [dbo].[Categorizes]  WITH CHECK ADD  CONSTRAINT [FK_Categorizes_Tag] FOREIGN KEY([TName])
REFERENCES [dbo].[Tag] ([TName])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Categorizes] CHECK CONSTRAINT [FK_Categorizes_Tag]
GO

