USE [master]
GO

/****** Object:  Database [ReallyBigGameDatabase]    Script Date: 2/19/2017 2:19:23 PM ******/
CREATE DATABASE [ReallyBigGameDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReallyBigDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TITAN\MSSQL\DATA\ReallyBigDatabase.mdf' , SIZE = 7552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ReallyBigDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TITAN\MSSQL\DATA\ReallyBigDatabase_log.ldf' , SIZE = 32448KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ReallyBigGameDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReallyBigGameDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReallyBigGameDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReallyBigGameDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ReallyBigGameDatabase] SET  READ_WRITE 
GO

